#!/bin/bash
# Start Minifigure-Stonks on local network
# Allows access from other devices on your WiFi

set -e

echo "=========================================="
echo "Minifigure-Stonks Network Startup"
echo "=========================================="
echo ""

# Detect local IP address
echo "🔍 Detecting local IP address..."
LOCAL_IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo "")

if [ -z "$LOCAL_IP" ]; then
    echo "❌ Could not detect local IP address"
    echo "Please find your IP manually with: ifconfig | grep 'inet '"
    exit 1
fi

echo "✓ Local IP detected: $LOCAL_IP"
echo ""

# Create frontend .env.local file
echo "📝 Configuring frontend environment..."
cat > frontend/.env.local <<EOF
# Auto-generated by start-network.sh
# This allows the frontend to connect to the backend on your local network
NEXT_PUBLIC_API_URL=http://${LOCAL_IP}:8000/v1
EOF
echo "✓ Created frontend/.env.local"
echo ""

# Display access information
echo "=========================================="
echo "🌐 Network Access Information"
echo "=========================================="
echo ""
echo "Access from ANY device on your WiFi:"
echo "  Frontend: http://${LOCAL_IP}:3000"
echo "  Backend:  http://${LOCAL_IP}:8000"
echo "  API Docs: http://${LOCAL_IP}:8000/v1/docs"
echo ""
echo "From this computer, you can still use:"
echo "  Frontend: http://localhost:3000"
echo "  Backend:  http://localhost:8000"
echo ""
echo "=========================================="
echo ""

# Check if services are already running
if lsof -Pi :8000 -sTCP:LISTEN -t >/dev/null 2>&1; then
    echo "⚠️  Backend is already running on port 8000"
    echo "   Kill it first with: lsof -ti:8000 | xargs kill -9"
    echo ""
fi

if lsof -Pi :3000 -sTCP:LISTEN -t >/dev/null 2>&1; then
    echo "⚠️  Frontend is already running on port 3000"
    echo "   Kill it first with: lsof -ti:3000 | xargs kill -9"
    echo ""
fi

# Start backend
echo "🚀 Starting backend on ${LOCAL_IP}:8000..."
cd backend
source venv/bin/activate
python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload &
BACKEND_PID=$!
cd ..
echo "✓ Backend started (PID: $BACKEND_PID)"
echo ""

# Wait for backend to be ready
echo "⏳ Waiting for backend to be ready..."
sleep 3

# Start frontend
echo "🚀 Starting frontend on ${LOCAL_IP}:3000..."
cd frontend
npm run dev -- -H 0.0.0.0 &
FRONTEND_PID=$!
cd ..
echo "✓ Frontend started (PID: $FRONTEND_PID)"
echo ""

# Save PIDs for cleanup
echo "$BACKEND_PID" > .backend.pid
echo "$FRONTEND_PID" > .frontend.pid

echo "=========================================="
echo "✅ Services Started Successfully!"
echo "=========================================="
echo ""
echo "Access URLs:"
echo "  • Frontend: http://${LOCAL_IP}:3000"
echo "  • Backend:  http://${LOCAL_IP}:8000/v1/docs"
echo ""
echo "To stop services, press Ctrl+C or run:"
echo "  ./stop-network.sh"
echo ""
echo "Logs will appear below..."
echo "=========================================="
echo ""

# Wait for user interrupt
trap "echo ''; echo '🛑 Stopping services...'; kill $BACKEND_PID $FRONTEND_PID 2>/dev/null; rm -f .backend.pid .frontend.pid; echo '✓ Services stopped'; exit 0" INT TERM

# Keep script running and show that services are active
wait
